// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nuupfjiavbqyeuamrydv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51dXBmamlhdmJxeWV1YW1yeWR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MTY2NzQsImV4cCI6MjA2NzQ5MjY3NH0.cxOh379rjeXenwxwia6TVV0lse_FrMThzI9cfOsfxMg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});